import './globals.css'
import Header from '../components/FHeader';
import localfont from 'next/font/local'

const ablition = localfont(
  {
    src: [{
      path: "../../public/Fonts/Ablation.otf",
      weight: "400"
    }],
    variable: "--font-ablition"
  }
)

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="theme-color" content="#111" />
      </head>
      <body
        className={`
           ${ablition.className}
        `}
      >
        <Header />
        {children}
      </body>
    </html>
  )
}
